---
- hosts: nodes

  become: true

  tasks:
    - name: Find node's interface name                                                                                        
    command: "ip route | grep default|awk '{print $5;exit}''"
      register: node_interface_name

    - name: "Configuring interface {{node_interface_name.stdout}}"                                                            
      nmcli:
        conn_name: "{{node_interface_name.stdout}}"                                                                             
        ifname: "{{node_interface_name.stdout}}"
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "10.10.10.243"                                                                                                     
        gw4: "10.10.10.1" 