---
- hosts: nodes

  become: true

  tasks:
    - name: Install NetworkManager-glib
      yum: 
        name: NetworkManager-glib
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Find node's interface name                                                                                        
      shell: | 
        ip route | grep default | awk '{print $5;exit}'
      register: node_interface_name

    - name: "Configuring interface {{node_interface_name.stdout}}"                                                            
      nmcli:
        conn_name: "{{node_interface_name.stdout}}"                                                                             
        ifname: "{{node_interface_name.stdout}}"
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "10.10.10.243"                                                                                                     
        gw4: "10.10.10.1" 
      when: ansible_os_family == "RedHat"

    - name: "Update Debian-based interfaces IP"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)10.10.10.244(.*)$'
        line: '        address 10.10.10.243'
      when: ansible_os_family == "Debian"

    - name: "Update Debian-based interfaces gateway"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)10.10.10.1(.*)$'
        line: '        gateway 10.10.10.1'
      when: ansible_os_family == "Debian"

    - name: "Remove auxilary Debian-based interfaces network attribute"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)network(.*)$'
        state: absent
      when: ansible_os_family == "Debian"

    - name: "Remove auxilary Debian-based interfaces broadcast attribute"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)broadcast(.*)$'
        state: absent
      when: ansible_os_family == "Debian"

    - name: Restart machine
      shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
      async: 1
      poll: 0
      become: true