---
- hosts: nodes

  vars_files:
      - provision.yml

  become: true

  tasks:
    - name: Find node's interface name                                                                                        
      shell: | 
        ip route | grep default | awk '{print $5;exit}'
      register: node_interface_name

    - name: "Configuring interface {{node_interface_name.stdout}}"                                                            
      nmcli:
        conn_name: "{{node_interface_name.stdout}}"                                                                             
        ifname: "{{node_interface_name.stdout}}"
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "{{ip}}"                                                                                                     
        gw4: "{{gw}}" 
        dns4: "1.1.1.1"
      when: ansible_os_family == "RedHat"

    - name: "Update Debian-based interfaces IP"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: "^(.*)169.254.250.250(.*)$"
        line: "        address {{ip}}"
      when: ansible_os_family == "Debian"

    - name: "Update Debian-based interfaces gateway"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)169.254.251.251(.*)$'
        line: '        gateway {{gw}}'
      when: ansible_os_family == "Debian"

    - name: "Update Debian-based interfaces DNS"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)dns-nameservers(.*)$'
        line: '        dns-nameservers 1.1.1.1'
      when: ansible_os_family == "Debian"

    - name: "Remove auxilary Debian-based interfaces network attribute"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)network(.*)$'
        state: absent
      when: ansible_os_family == "Debian"

    - name: "Remove auxilary Debian-based interfaces broadcast attribute"
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(.*)broadcast(.*)$'
        state: absent
      when: ansible_os_family == "Debian"
      
    - name: "Replace APT repository from install time in /etc/apt/sources.list"
      replace: 
        dest: /etc/apt/sources.list
        regexp: '(169.254.254.254:8080)'
        replace: 'mirrors.mit.edu'
      when: ansible_os_family == "Debian"

    - name: Restart machine
      shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
      async: 1
      poll: 0
      become: true